<?php

/**
 * @file
 * United Arab Emirates.
 */

/**
 * Returns an associative array of states/territories.
 */
function location_province_list_ae() {
  return array(
    'AZ' => "Abu Dhabi",
    'AJ' => "'Ajman",
    'FU' => "Fujairah",
    'SH' => "Sharjah",
    'DU' => "Dubai",
    'RK' => "Ras al-Khaimah",
    'UQ' => "Umm al-Qaiwain"
  );
}

/**
 * Returns minimum and maximum latitude and longitude needed to create a bounding box.
 */
function location_bounds_ae() {
  return array(
    'minlng' => 50.7756,
    'minlat' => 22.540493,
    'maxlng' => 56.3684,
    'maxlat' => 26.241233,
  );
}





 



